// Generated by scripts/gen-abi.mjs from the forge artefacts. Do not edit by hand.

export const ROUTER_ABI = [
  {
    "type": "function",
    "name": "REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IProviderRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SERVICE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IClprService"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "VAULT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IQuarantineVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "flush",
    "inputs": [
      {
        "name": "channelId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "connectorId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "target",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "forward",
    "inputs": [
      {
        "name": "envelope",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "newTail",
        "type": "tuple[]",
        "internalType": "struct RouteTypes.Hop[]",
        "components": [
          {
            "name": "ledgerId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "router",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "channelId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "connectorId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "fee",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "feePayee",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hopState",
    "inputs": [
      {
        "name": "",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum ClprRouter.HopState"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ledgerId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "outbox",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingHash",
    "inputs": [
      {
        "name": "",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "routes",
    "inputs": [
      {
        "name": "",
        "type": "bytes16",
        "internalType": "bytes16"
      }
    ],
    "outputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "deadline",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum ClprRouter.RouteStatus"
      },
      {
        "name": "strict",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "verifyPath",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "payee",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeBudget",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "escrow",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "hopsHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "firstHop",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ForwardPending",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "hopIndex",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "envelope",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ForwardRejected",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "clprStatus",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "envelope",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HopResponse",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "channelId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "messageId",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OutboxQueued",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "channelId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "connectorId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "target",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "data",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "QuarantineNotice",
    "inputs": [
      {
        "name": "recipientKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "recipient",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "contact",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReceiptIgnored",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReceiptSent",
    "inputs": [
      {
        "name": "receiptId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RouteTypes.ReceiptStatus"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RouteTypes.Reason"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReceiptUndeliverable",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RouteTypes.Reason"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteDelivered",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "application",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "responseHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteForwarded",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "hopIndex",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "channelId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "messageId",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteSent",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "destinationLedger",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "escrow",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "feeBudget",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "deadline",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "messageId",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteSettled",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum ClprRouter.RouteStatus"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RouteTypes.Reason"
      },
      {
        "name": "hopIndex",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "contact",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "feesPaid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteStopped",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "hopIndex",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RouteTypes.ReceiptStatus"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RouteTypes.Reason"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DuplicateRouteId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRoute",
    "inputs": [
      {
        "name": "reason",
        "type": "uint8",
        "internalType": "enum RouteTypes.Reason"
      }
    ]
  },
  {
    "type": "error",
    "name": "LedgerMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LooseRoutingRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotForThisHop",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotReclaimable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotService",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RouteBlocked",
    "inputs": [
      {
        "name": "hop",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reason",
        "type": "uint8",
        "internalType": "enum RouteTypes.Reason"
      }
    ]
  },
  {
    "type": "error",
    "name": "RouteReplayed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnexpectedSender",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ValueRoutesMustBeStrict",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongVersion",
    "inputs": []
  }
] as const;

export const REGISTRY_ABI = [
  {
    "type": "function",
    "name": "BLACKLIST_LAPSE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DISABLE_LAPSE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "blacklisted",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "listed",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "certificationAt",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "atVersion",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "certified",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "emissionsUg",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "certificationLog",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct ProviderRegistry.Certification[]",
        "components": [
          {
            "name": "version",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "effectiveFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "certified",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "emissionsUg",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "evidenceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "contact",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epoch",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isDisabled",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "members",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "threshold",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "version",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AccountBlacklisted",
    "inputs": [
      {
        "name": "accountKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "caip10",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "lapseAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "renewed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "reason",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AccountDelisted",
    "inputs": [
      {
        "name": "accountKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "caip10",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "applied",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CertificationScheduled",
    "inputs": [
      {
        "name": "certKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "ledgerId",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "label",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "certified",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "effectiveFrom",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "emissionsUg",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "emissionsSource",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CommitteeChanged",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "members",
        "type": "address[]",
        "indexed": false,
        "internalType": "address[]"
      },
      {
        "name": "threshold",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ContactChanged",
    "inputs": [
      {
        "name": "contact",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DecisionApplied",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "action",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteDisabled",
    "inputs": [
      {
        "name": "kind",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "subject",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "lapseAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "renewed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "reason",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteReenableScheduled",
    "inputs": [
      {
        "name": "kind",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "subject",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reenableAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecisionAlreadyUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecisionExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientSignatures",
    "inputs": [
      {
        "name": "valid",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidCommittee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExpiry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLabel",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTarget",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MissingEmissions",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MissingEvidence",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OutOfOrder",
    "inputs": [
      {
        "name": "expectedNonce",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "nonce",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "SignersNotSorted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedAction",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongEpoch",
    "inputs": []
  }
] as const;

export const VAULT_ABI = [
  {
    "type": "function",
    "name": "depositCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposits",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "routeId",
        "type": "bytes16",
        "internalType": "bytes16"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "depositor",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "released",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recoveries",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "namedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "releasableAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "challenged",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Deposited",
    "inputs": [
      {
        "name": "depositId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "routeId",
        "type": "bytes16",
        "indexed": true,
        "internalType": "bytes16"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "depositor",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RecoveryChallenged",
    "inputs": [
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RecoveryNamed",
    "inputs": [
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "releasableAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Released",
    "inputs": [
      {
        "name": "depositId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "caseId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "kind",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum QuarantineVault.Beneficiary"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyReleased",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CaseMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ChallengeClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecisionAlreadyUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecisionExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ForbiddenBeneficiary",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MissingEvidence",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoCase",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoFunds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAParty",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RecoveryNotReady",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownDeposit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongAction",
    "inputs": []
  }
] as const;

