// Regenerates src/abi.ts from the forge artefacts in ../out (run `forge build` in the repo root first).
// Only events and the functions the services call are kept, so the services do not depend on the build at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const out = fileURLToPath(new URL("../../out/", import.meta.url));
const pick = {
  ROUTER_ABI: ["ClprRouter.sol/ClprRouter.json", ["forward", "flush", "hopState", "pendingHash", "outbox", "routes", "ledgerId", "VERSION", "REGISTRY", "VAULT", "SERVICE"]],
  REGISTRY_ABI: ["ProviderRegistry.sol/ProviderRegistry.json", ["version", "epoch", "threshold", "members", "contact", "isDisabled", "blacklisted", "certificationAt", "certificationLog", "DISABLE_LAPSE", "BLACKLIST_LAPSE"]],
  VAULT_ABI: ["QuarantineVault.sol/QuarantineVault.json", ["deposits", "depositCount", "recoveries"]],
};
let src = "// Generated by scripts/gen-abi.mjs from the forge artefacts. Do not edit by hand.\n\n";
for (const [name, [file, fns]] of Object.entries(pick)) {
  const abi = JSON.parse(readFileSync(out + file, "utf8")).abi;
  const kept = abi.filter((x) => x.type === "event" || x.type === "error" || (x.type === "function" && fns.includes(x.name)));
  src += `export const ${name} = ${JSON.stringify(kept, null, 2)} as const;\n\n`;
}
writeFileSync(fileURLToPath(new URL("../src/abi.ts", import.meta.url)), src);
console.log("wrote src/abi.ts");
