// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {RouteTypes} from "@clprouter/libraries/RouteTypes.sol";
import {RouteCodec} from "@clprouter/libraries/RouteCodec.sol";

/// @notice Cross-implementation vectors for `ClprRouteEnvelope`: each vector is an envelope as `abi.encode`d
///         `RouteTypes.Envelope` plus the protobuf bytes `RouteCodec.encodeEnvelope` produces for it. The planner
///         SDK (sdk/test/vectors.test.ts) decodes the ABI form, encodes it with its own codec and must produce the
///         same bytes, and decodes the protobuf back to the same envelope.
///
///         This test fails if the committed fixture no longer matches the Solidity codec. Regenerate it with
///         `WRITE_VECTORS=true forge test --match-contract RouteCodecVectorsTest`.
contract RouteCodecVectorsTest is Test {
    string internal constant PATH = "sdk/test/vectors/route-envelope.json";

    function test_vectors_matchCommittedFixture() public {
        string memory json = _json();
        if (vm.envOr("WRITE_VECTORS", false)) vm.writeFile(PATH, json);
        assertEq(vm.readFile(PATH), json, "fixture is stale: regenerate with WRITE_VECTORS=true");
    }

    function test_vectors_roundTripInSolidity() public pure {
        RouteTypes.Envelope[] memory v = _vectors();
        for (uint256 i = 0; i < v.length; i++) {
            bytes memory enc = RouteCodec.encodeEnvelope(v[i]);
            assertEq(keccak256(abi.encode(RouteCodec.decodeEnvelope(enc))), keccak256(abi.encode(v[i])));
        }
    }

    // ── fixture ────────────────────────────────────────────────────────────

    function _json() internal pure returns (string memory out) {
        RouteTypes.Envelope[] memory v = _vectors();
        string[7] memory names = [
            "empty",
            "route-id-and-empty-hop",
            "full-three-hops",
            "uint-maxima",
            "receipt",
            "utf8-strings",
            "filters-iso-energy"
        ];
        out = string.concat(
            "{\n",
            '  "description": "ClprRouteEnvelope vectors generated by test/unit/RouteCodecVectors.t.sol: envelopeAbi = ',
            'abi.encode(RouteTypes.Envelope), protobuf = RouteCodec.encodeEnvelope(envelope).",\n',
            '  "vectors": [\n'
        );
        for (uint256 i = 0; i < v.length; i++) {
            out = string.concat(
                out,
                '    {\n      "name": "',
                names[i],
                '",\n      "envelopeAbi": "',
                vm.toString(abi.encode(v[i])),
                '",\n      "protobuf": "',
                vm.toString(RouteCodec.encodeEnvelope(v[i])),
                i + 1 < v.length ? '"\n    },\n' : '"\n    }\n'
            );
        }
        out = string.concat(out, "  ]\n}\n");
    }

    function _vectors() internal pure returns (RouteTypes.Envelope[] memory v) {
        v = new RouteTypes.Envelope[](7);

        // 1. Every field at its default: encodes to zero bytes.

        // 2. Route id and one hop whose fields are all default: the repeated element is still emitted.
        v[1].routeId = bytes16(0x0102030405060708090a0b0c0d0e0f10);
        v[1].hops = new RouteTypes.Hop[](1);
        v[1].routerVersion = 1;

        // 3. A three-hop route with every field set.
        RouteTypes.Envelope memory e = v[2];
        e.routeId = bytes16(0x8a1b2c3d4e5f40718293a4b5c6d7e8f9);
        e.origin = RouteTypes.Endpoint("eip155:31001", hex"1111111111111111111111111111111111111111");
        e.destination = RouteTypes.Endpoint("eip155:31003", hex"3333333333333333333333333333333333333333");
        e.sender = "eip155:31001:0x1111111111111111111111111111111111111111";
        e.recipient = "eip155:31003:0x3333333333333333333333333333333333333333";
        e.hops = new RouteTypes.Hop[](3);
        e.hops[0] = RouteTypes.Hop(
            "eip155:31001",
            hex"a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0",
            keccak256("AB"),
            keccak256("conn-AB"),
            0.01 ether,
            hex"fa00000000000000000000000000000000000001"
        );
        e.hops[1] = RouteTypes.Hop(
            "hedera:testnet",
            hex"b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0",
            keccak256("BC"),
            keccak256("conn-BC"),
            0.02 ether,
            hex"fb00000000000000000000000000000000000002"
        );
        e.hops[2] = RouteTypes.Hop("eip155:31003", hex"c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0", 0, 0, 0, "");
        e.hopIndex = 1;
        e.mode = RouteTypes.Mode.GREENEST;
        // filters ISO|MICA|ENERGY, deadline, max fee, remaining budget, trust floor light-client (2), max hops,
        // loose, energy cap 2400 µgCO2e
        e.constraints = RouteTypes.Constraints(7, 1_800_003_600, 0.05 ether, 0.04 ether, 2, 3, true, 2400);
        e.payloadType = RouteTypes.PayloadType.ISO20022;
        e.payload = abi.encodePacked(keccak256("pacs.008 ciphertext"));
        e.receiptPath = new RouteTypes.Hop[](3);
        e.receiptPath[0] = RouteTypes.Hop("eip155:31003", e.hops[2].router, keccak256("BC"), 0, 0, "");
        e.receiptPath[1] = RouteTypes.Hop("hedera:testnet", e.hops[1].router, keccak256("AB"), 0, 0, "");
        e.receiptPath[2] = RouteTypes.Hop("eip155:31001", e.hops[0].router, 0, 0, 0, "");
        e.originSignature = bytes.concat(keccak256("r"), keccak256("s"), hex"1b");
        e.filterRegistryVersions = new RouteTypes.RegistryVersion[](3);
        e.filterRegistryVersions[0] = RouteTypes.RegistryVersion(1, 42); // registry decision counter, not a time
        e.filterRegistryVersions[1] = RouteTypes.RegistryVersion(2, 42);
        e.filterRegistryVersions[2] = RouteTypes.RegistryVersion(4, 42);
        e.routerVersion = 1;

        // 4. Every integer at its maximum (10-byte varints for uint64).
        e = v[3];
        e.routeId = bytes16(type(uint128).max);
        e.hops = new RouteTypes.Hop[](2);
        e.hops[0] =
            RouteTypes.Hop("a:b", hex"01", bytes32(type(uint256).max), bytes32(uint256(1)), type(uint64).max, hex"02");
        e.hops[1] = RouteTypes.Hop("c:d", hex"03", 0, 0, 0, "");
        e.hopIndex = type(uint32).max;
        e.mode = RouteTypes.Mode.MOST_RELIABLE;
        e.constraints = RouteTypes.Constraints(
            7, type(uint64).max, type(uint64).max, type(uint64).max, 3, type(uint32).max, false, type(uint64).max
        );
        e.filterRegistryVersions = new RouteTypes.RegistryVersion[](1);
        e.filterRegistryVersions[0] = RouteTypes.RegistryVersion(4, type(uint64).max);
        e.routerVersion = type(uint32).max;

        // 5. A receipt envelope (payload is an encoded ClprRouteReceipt).
        e = v[4];
        e.routeId = bytes16(keccak256("receipt"));
        e.origin = RouteTypes.Endpoint("eip155:31003", hex"c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0");
        e.destination = RouteTypes.Endpoint("eip155:31001", hex"1111111111111111111111111111111111111111");
        e.hops = new RouteTypes.Hop[](2);
        e.hops[0] = RouteTypes.Hop(
            "eip155:31003", hex"c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0", keccak256("BC"), keccak256("k"), 0, ""
        );
        e.hops[1] = RouteTypes.Hop("eip155:31001", hex"a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0", 0, 0, 0, "");
        e.hopIndex = 1;
        e.mode = RouteTypes.Mode.FASTEST;
        e.payloadType = RouteTypes.PayloadType.RECEIPT;
        e.payload = hex"0a10000000000000000000000000000000051001180222";
        e.routerVersion = 1;

        // 6. Multi-byte UTF-8 in string fields (encoded as raw UTF-8 bytes).
        e = v[5];
        e.sender = unicode"eip155:1:0xÄbc-ü";
        e.recipient = unicode"hedera:mainnet:0.0.12–34 ✓";
        e.origin = RouteTypes.Endpoint(unicode"ledger:ñ", "");
        e.mode = RouteTypes.Mode.CHEAPEST;
        e.payloadType = RouteTypes.PayloadType.ASSET;
        e.payload = hex"00ff00ff";

        // 7. Two of three filters (ISO 20022 + Energy), strict, validity-proof floor.
        e = v[6];
        e.routeId = bytes16(uint128(1));
        e.constraints = RouteTypes.Constraints(5, 300, 0, 0, 3, 0, false, 1);
        e.filterRegistryVersions = new RouteTypes.RegistryVersion[](2);
        e.filterRegistryVersions[0] = RouteTypes.RegistryVersion(1, 1);
        e.filterRegistryVersions[1] = RouteTypes.RegistryVersion(4, 1);
        e.mode = RouteTypes.Mode.BALANCED;
        e.payloadType = RouteTypes.PayloadType.ISO20022;
        e.isoUetr = bytes16(0x8a1b2c3d4e5f40718293a4b5c6d7e8f9); // UETR in its own field (iso_uetr = 16)
    }
}
